// <auto-generated />
using System;
using DataAccessLayer.Abstract;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Firma", b =>
                {
                    b.Property<int>("firmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("firmaAd")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("iletisim")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("logoUrl")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<bool>("silindi")
                        .HasColumnType("bit");

                    b.HasKey("firmaId");

                    b.ToTable("firmalar");
                });

            modelBuilder.Entity("EntityLayer.Guzergah", b =>
                {
                    b.Property<int>("guzergahId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("kalkisYeri")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("varisYeri")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("guzergahId");

                    b.ToTable("guzergahlar");
                });

            modelBuilder.Entity("EntityLayer.GuzergahOtobus", b =>
                {
                    b.Property<int>("seferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("biletFiyat")
                        .HasColumnType("float");

                    b.Property<int>("guzergahId")
                        .HasColumnType("int");

                    b.Property<string>("kalkisSaat")
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.Property<int>("otobusId")
                        .HasColumnType("int");

                    b.Property<int>("sure")
                        .HasColumnType("int");

                    b.Property<DateTime>("tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("seferId");

                    b.HasIndex("guzergahId");

                    b.HasIndex("otobusId");

                    b.ToTable("guzergahOtobusler");
                });

            modelBuilder.Entity("EntityLayer.GuzergahOtobusKullanici", b =>
                {
                    b.Property<int>("biletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("biletKesimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("guzergahOtobusId")
                        .HasColumnType("int");

                    b.Property<int>("koltukNo")
                        .HasColumnType("int");

                    b.Property<int>("kullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("odemeTipi")
                        .HasColumnType("bit");

                    b.Property<string>("seriNo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("yolcuAd")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool>("yolcuCinsiyet")
                        .HasColumnType("bit");

                    b.Property<string>("yolcuSoyad")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("yolcuTc")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("biletId");

                    b.HasIndex("guzergahOtobusId");

                    b.HasIndex("kullaniciId");

                    b.ToTable("guzergahOtobusKullanicilar");
                });

            modelBuilder.Entity("EntityLayer.Kullanici", b =>
                {
                    b.Property<int>("kullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("cinsiyet")
                        .HasColumnType("bit");

                    b.Property<DateTime>("dogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("kullaniciAd")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("kullaniciSifre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("soyad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("tc")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("tel")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("kullaniciId");

                    b.ToTable("kullanicilar");
                });

            modelBuilder.Entity("EntityLayer.Otobus", b =>
                {
                    b.Property<int>("otobusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("firmaId")
                        .HasColumnType("int");

                    b.Property<int>("koltukSayisi")
                        .HasColumnType("int");

                    b.Property<string>("marka")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("plaka")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<bool>("tv")
                        .HasColumnType("bit");

                    b.Property<bool>("wifi")
                        .HasColumnType("bit");

                    b.HasKey("otobusId");

                    b.HasIndex("firmaId");

                    b.ToTable("otobusler");
                });

            modelBuilder.Entity("EntityLayer.GuzergahOtobus", b =>
                {
                    b.HasOne("EntityLayer.Guzergah", "guzergah")
                        .WithMany("guzergahOtobusler")
                        .HasForeignKey("guzergahId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Otobus", "otobus")
                        .WithMany("guzergahOtobusler")
                        .HasForeignKey("otobusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.GuzergahOtobusKullanici", b =>
                {
                    b.HasOne("EntityLayer.GuzergahOtobus", "guzergahOtobus")
                        .WithMany("biletler")
                        .HasForeignKey("guzergahOtobusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Kullanici", "kullanici")
                        .WithMany("biletler")
                        .HasForeignKey("kullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Otobus", b =>
                {
                    b.HasOne("EntityLayer.Firma", "firma")
                        .WithMany("otobusler")
                        .HasForeignKey("firmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
